### PR TITLE
pygit2: bump to 1.14.0

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
* https://github.com/libgit2/pygit2/pull/1259

### CODE REVIEW

**Comment by efiop** [comment]
We need to drop 3.8 first, will do in a separate PR in a sec...

**Comment by 0x2b3bfa0** [comment]
@efiop, shall I revert 3095ebc7bdb9cc2e06dbd8bf27029b40710409a7 then? :fastpoke:

**Comment by efiop** [comment]
@0x2b3bfa0 Nah, let's keep it then.

**Review by efiop — DISMISSED** [review]

**Review by efiop — APPROVED** [review]

**Review by efiop — APPROVED** [review]
:fastpoke: Thanks for adding 3.12 as well! 🙏

**Review by shcheklein — APPROVED** [review]
Thanks @0x2b3bfa0 !

**Comment by 0x2b3bfa0** [comment]
Ubuntu on Python 3.9 was failing ([run](https://github.com/iterative/scmrepo/actions/runs/7686944906/job/20946408423)); hoping to get it fixed with https://github.com/iterative/scmrepo/pull/312/commits/649a13052893dff09241bd8008a59d107a58a000

**Review by efiop — APPROVED** [review]
Great work @0x2b3bfa0 !

**Pull request merged**
