### PR TITLE
lfs: replace wrap_and_branch_coro with equivalent

### PR DESCRIPTION
**Pull request by skshetry**

### CODE REVIEW

**Comment by skshetry** [comment]
It's unclear to me why we are even using `dvc-http` and `dvc-objects` here.

**Comment by skshetry** [comment]
I'm running with this to unblock https://github.com/iterative/dql/pull/1058.

**Comment by pmrowla** [comment]
> It's unclear to me why we are even using `dvc-http` and `dvc-objects` here.

It's so we can reuse the logic for batched transfers and the aiohttp large download timeouts. I didn't see the point in copy/pasting everything from dvc-http and dvc-objects generic transfer into scmrepo

**Comment by skshetry** [comment]
dvc-http is a dvc's plugin. I have fixed the immediate issue, but we are creating a circular dependency issue here with this.

Maybe we can add support for batched transfers for fsspec filesystems in dvc-objects?
The aiohttp large download timeouts fixes are small that we can copy it here as well (or upstream it to fsspec).

Ideally, the fix would be to not have our own wrappers.

**Pull request merged**
