### PR TITLE
gha: run tests in pypy

### PR DESCRIPTION
**Pull request by skshetry**

### CODE REVIEW

**Comment by skshetry** [comment]
Tests are failing due to https://foss.heptapod.net/pypy/pypy/-/issues/3168.

**Comment by efiop** [comment]
@skshetry looks like just need to implicitly covert in our tests and that should fix it?

**Comment by skshetry** [comment]
yes, we need to convert pathlib to fspaths ourselves.

**Comment by skshetry** [comment]
> @skshetry looks like just need to implicitly covert in our tests and that should fix it?

This is something that needs to be fixed in pygit2; we need to add compat APIs for supporting Path objects in PyPy.

**Pull request merged**
