### PR TITLE
bump to 0.0.23

### PR DESCRIPTION
**Pull request by dtrifiro**

### CODE REVIEW

**Comment by dtrifiro** [comment]
Actually, please hold on, there is one extra thing I want to do before bumping version :pray:

**Comment by dtrifiro** [comment]
I'd be happy to also include https://github.com/iterative/scmrepo/pull/74 in 0.0.23

**Comment by efiop** [comment]
@dtrifiro We also need to put an upper bound on dulwich, so we have the wheels.

**Comment by dtrifiro** [comment]
I'll test `0.20.39`, and wait for that to be [tagged](https://github.com/jelmer/dulwich/tags)

**Comment by skshetry** [comment]
Closing this, now there's no need to manually bump the version. Just create the release from GitHub UI, and it'll automatically publish (thanks to `setuptools_scm`).

**Pull request closed without merging**
