### PR TITLE
status: add warning on slow status call

### PR DESCRIPTION
**Pull request by dtrifiro**
While playing with `dvc exp`, I noticed that it would take a huge amount of time before getting any output.

I tracked this down to [`dvc/repo/experiments/__init__.py#L401`](https://github.com/iterative/dvc/blob/cd65400d83df9ede8f25317a413fe2da5ba05ff3/dvc/repo/experiments/__init__.py#L401): a `self.scm.status()` was taking a long time because of a large untracked directory (`.venv`  virtualenv folder).

This is a kinda naive patch that prints a warning whenever it takes more than 10s for status to return.  I don't intend for this to be merged, rather to be a starting point for a discussion.

### CODE REVIEW

**Comment by dtrifiro** [comment]
See https://github.com/iterative/dvc/issues/7471

**Comment by pmrowla** [comment]
We probably should just submit an upstream patch to optimize dulwich `porcelain.status` with an option to skip walking untracked directories on status (similar to the existing option to skip walking ignored directories)

https://github.com/jelmer/dulwich/blob/0aa42073297748b07f5d176557b2357e87ddffbe/dulwich/porcelain.py#L1218

**Comment by dtrifiro** [comment]
Good point, I'll have a look

**Comment by dtrifiro** [comment]
Opened https://github.com/jelmer/dulwich/pull/956, will open a new one here when/if that is merged

**Comment by dtrifiro** [comment]
Getting rid of this, ended up implenting Peter's suggestion in #69

**Pull request closed without merging**
